### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by marco-david** [ColinRothgang/Proposal-of-Rules-of-Procedure-for-Committees#1]
Footnote 1: I don't think the names of all votes should be recorded by default. Too much of a hassle. The numbers, yes. "Roll call voting" should only be in exceptional cases.

**Comment by ColinRothgang** [comment]
In good memory of last meeting I can only agree. I changed it accordingly.

**Comment by marco-david** [comment]
Thank you. I just committed my package to your minutes repo. If possible, could you adopt this proposal into the respective style and upload it again on Teamwork?
